// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_uY7ObmPnROF-wF3tgHD74je55M9qM7g',
    appId: '1:412628730632:web:02368b95efe538d92422bd',
    messagingSenderId: '412628730632',
    projectId: 'sample-firebase-ai-app-a3fbe',
    authDomain: 'sample-firebase-ai-app-a3fbe.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-a3fbe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-o0wZKUKisNRqAtKAG_XIKW9xXFc4SXo',
    appId: '1:412628730632:android:b5230ba7517b5da62422bd',
    messagingSenderId: '412628730632',
    projectId: 'sample-firebase-ai-app-a3fbe',
    storageBucket: 'sample-firebase-ai-app-a3fbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA4-JoiXdhJT2hjRFPqYc_A9UHt3EcTM0',
    appId: '1:412628730632:ios:228ef32f616f4dc22422bd',
    messagingSenderId: '412628730632',
    projectId: 'sample-firebase-ai-app-a3fbe',
    storageBucket: 'sample-firebase-ai-app-a3fbe.firebasestorage.app',
    iosBundleId: 'com.example.smartSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA4-JoiXdhJT2hjRFPqYc_A9UHt3EcTM0',
    appId: '1:412628730632:ios:228ef32f616f4dc22422bd',
    messagingSenderId: '412628730632',
    projectId: 'sample-firebase-ai-app-a3fbe',
    storageBucket: 'sample-firebase-ai-app-a3fbe.firebasestorage.app',
    iosBundleId: 'com.example.smartSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_uY7ObmPnROF-wF3tgHD74je55M9qM7g',
    appId: '1:412628730632:web:2a91554cac4bb4b42422bd',
    messagingSenderId: '412628730632',
    projectId: 'sample-firebase-ai-app-a3fbe',
    authDomain: 'sample-firebase-ai-app-a3fbe.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-a3fbe.firebasestorage.app',
  );

}