// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKUgm-MEI-UTMUbbCDdFKttiMUI0rXYtk',
    appId: '1:1078214539972:web:d2dc8fd14272ef1af76791',
    messagingSenderId: '1078214539972',
    projectId: 'smart-school-ca690',
    authDomain: 'smart-school-ca690.firebaseapp.com',
    storageBucket: 'smart-school-ca690.firebasestorage.app',
    measurementId: 'G-F2KMXS0GVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIsF6tpY1TAAP16IbKLOj3tCPTk_B4jiI',
    appId: '1:1078214539972:android:94d2f09315324d8af76791',
    messagingSenderId: '1078214539972',
    projectId: 'smart-school-ca690',
    storageBucket: 'smart-school-ca690.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgWkYwlMcPAnVLyKU3NxKdTZnliJ0cNcQ',
    appId: '1:1078214539972:ios:d4cd3f7116df9b8ff76791',
    messagingSenderId: '1078214539972',
    projectId: 'smart-school-ca690',
    storageBucket: 'smart-school-ca690.firebasestorage.app',
    iosBundleId: 'com.example.smartSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgWkYwlMcPAnVLyKU3NxKdTZnliJ0cNcQ',
    appId: '1:1078214539972:ios:d4cd3f7116df9b8ff76791',
    messagingSenderId: '1078214539972',
    projectId: 'smart-school-ca690',
    storageBucket: 'smart-school-ca690.firebasestorage.app',
    iosBundleId: 'com.example.smartSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKUgm-MEI-UTMUbbCDdFKttiMUI0rXYtk',
    appId: '1:1078214539972:web:785f59bb3312fe3bf76791',
    messagingSenderId: '1078214539972',
    projectId: 'smart-school-ca690',
    authDomain: 'smart-school-ca690.firebaseapp.com',
    storageBucket: 'smart-school-ca690.firebasestorage.app',
    measurementId: 'G-GEV8STRQ05',
  );

}