name: smart_school
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../packages/core
  auth:
    path: ../../packages/auth
  dues:
    path: ../../packages/dues
  homework:
    path: ../../packages/homework
  notification:
    path: ../../packages/notification
  profile:
    path: ../../packages/profile
  resource:
    path: ../../packages/resource
  subject:
    path: ../../packages/subject
  teacher_feat:
    path: ../../packages/teacher_feat
  attendance:
    path: ../../packages/attendance

  dio: ^5.3.3
  easy_localization: ^3.0.7+1
  flutter_bloc: ^8.1.6
  flutter_spinkit: ^5.2.0
  connectivity_plus: ^5.0.1
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.3
  calendar_date_picker2: ^2.0.1
  image_picker: ^1.1.2
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^8.0.3
  url_launcher: ^6.3.1
  go_router: ^15.1.3
  flutter_svg: ^1.1.6
  flutter_countdown_timer: ^4.1.0
  pinput: ^2.2.12
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  google_generative_ai: ^0.4.7
  flutter_chat_ui: ^2.5.2
  flutter_chat_core: ^2.0.0
  uuid: ^4.5.1
  sizer: ^3.0.5
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.0
  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/translations/
    - assets/auth_icons/
  generate: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700