name: teacher_feat
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: 'none'
environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  core:
    path: ../core
  shared_preferences: ^2.2.3
  get_it: ^8.0.3
  dartz: ^0.10.1


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
