name: attendance
description: Attendance feature package for smart school
version: 1.0.0

publish_to: 'none'
environment:
  sdk: ^3.7.2

dependencies:
  core:
    path: ../core
  dartz: ^0.10.1
  get_it: ^8.0.3
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  dio: ^5.8.0+1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0